---
sidebar: sidebar 
permalink: trident-get-started/requirements.html 
keywords: trident requirements, supported front ends, supported backends, kubernetes cluster, cluster requirements, version requirements, supported versions, host configuration, host os, system configuration, host operating system, fsx 
summary: Comece revisando os front-ends, backends e configuração de host suportados. 
---
= Requisitos
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Comece revisando os front-ends, backends e configuração de host suportados.


NOTE: Para saber mais sobre as portas que o Astra Trident usa, link:../trident-reference/trident-ports.html["aqui"^]consulte .



== Frontens suportados (orquestradores)

O Astra Trident é compatível com vários mecanismos de contêiner e orquestradores, incluindo os seguintes:

* Anthos On-Prem (VMware) e Anthos em bare metal 1,8, 1,9, 1,10
* Kubernetes 1,17 ou posterior (mais recente: 1,23)
* Mecanismo do Kubernetes do Mirantis 3,4
* OpenShift 4,7, 4,8, 4,9


O operador Trident é suportado com estas versões:

* Anthos On-Prem (VMware) e Anthos em bare metal 1,8, 1,9, 1,10
* Kubernetes 1,17 ou posterior (mais recente: 1,23)
* OpenShift 4,7, 4,8, 4,9



NOTE: Os usuários do Red Hat OpenShift Container Platform podem observar seu arquivo iniciatorname.iscsi para ficar em branco se estiver usando qualquer versão abaixo de 4,6.8. Este é um bug que foi identificado pela RedHat para ser corrigido com OpenShift 4,6.8. Consulte este https://access.redhat.com/errata/RHSA-2020:5259/["anúncio de correção de bugs"^]. A NetApp recomenda que você use o Astra Trident no OpenShift 4.6.8 e posterior.

O Astra Trident também trabalha com uma série de outras ofertas do Kubernetes totalmente gerenciadas e autogeridas, incluindo o Google Kubernetes Engine (GKE), o Amazon Elastic Kubernetes Services (EKS), o Azure Kubernetes Service (AKS), o Rancher e o portfólio VMware Tanzu.



== Backends suportados (armazenamento)

Para usar o Astra Trident, você precisa de um ou mais dos seguintes back-ends compatíveis:

* Amazon FSX para NetApp ONTAP
* Azure NetApp Files
* Armazenamento de dados Astra
* Cloud Volumes ONTAP
* Cloud Volumes Service para GCP
* FAS/AFF/Selecione 9,3 ou posterior
* NetApp All SAN Array (ASA)
* Software NetApp HCI/Element 11 ou posterior




== Requisitos de recursos

A tabela abaixo resume os recursos disponíveis com esta versão do Astra Trident e as versões do Kubernetes compatíveis.

[cols="3"]
|===
| Recurso | Versão do Kubernetes | É necessário ter portões? 


| CSI Trident  a| 
1,17 e mais tarde
 a| 
Não



| Instantâneos de volume  a| 
1,17 e mais tarde
 a| 
Não



| PVC a partir de instantâneos de volume  a| 
1,17 e mais tarde
 a| 
Não



| Redimensionamento iSCSI PV  a| 
1,17 e mais tarde
 a| 
Não



| ONTAP bidirectional CHAP  a| 
1,17 e mais tarde
 a| 
Não



| Políticas de exportação dinâmica  a| 
1,17 e mais tarde
 a| 
Não



| Operador Trident  a| 
1,17 e mais tarde
 a| 
Não



| Preparação do nó de trabalho automático (beta)  a| 
1,17 e mais tarde
 a| 
Não



| Topologia de CSI  a| 
1,17 e mais tarde
 a| 
Não

|===


== Sistemas operacionais de host testados

Por padrão, o Astra Trident é executado em um contentor e, portanto, será executado em qualquer trabalhador Linux. No entanto, esses funcionários precisam ser capazes de montar os volumes que o Astra Trident fornece usando o cliente NFS padrão ou iniciador iSCSI, dependendo dos backends que você está usando.

Embora o Astra Trident não "ofereça suporte" oficialmente a sistemas operacionais específicos, as seguintes distribuições Linux são conhecidas por funcionar:

* Versões do RedHat CoreOS (RHCOS) suportadas pela OpenShift Container Platform
* RHEL ou CentOS 7,4 ou posterior
* Ubuntu 18,04 ou posterior


O `tridentctl` utilitário também é executado em qualquer uma dessas distribuições do Linux.



== Configuração de host

Dependendo do(s) back-end(s) em uso, os utilitários NFS e/ou iSCSI devem ser instalados em todos os trabalhadores do cluster. Consulte link:../trident-use/worker-node-prep.html["aqui"^] para obter mais informações.



== Configuração do sistema de storage

O Astra Trident pode exigir algumas alterações em um sistema de storage antes que uma configuração de back-end o use. link:../trident-use/backends.html["aqui"^]Consulte para obter detalhes.



== Imagens de contêineres e versões correspondentes do Kubernetes

Para instalações com conexão de ar, a lista a seguir é uma referência das imagens de contêiner necessárias para instalar o Astra Trident. Use o `tridentctl images` comando para verificar a lista de imagens de contentor necessárias.

[cols="2"]
|===
| Versão do Kubernetes | Imagem do recipiente 


| v1.17.0  a| 
* NetApp/Trident:22.01.1
* NetApp/Trident-AutoSupport:22,01
* k8s.gcr.io/sig-storage/csi-provisionador:v2,2.2
* k8s.gcr.io/sig-storage/csi-attacher:v3,4.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3,0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrador:v2.4.0
* NetApp/Trident-operador: 22.01.1 (opcional)




| v1.18.0  a| 
* NetApp/Trident:22.01.1
* NetApp/Trident-AutoSupport:22,01
* k8s.gcr.io/sig-storage/csi-provisionador:v2,2.2
* k8s.gcr.io/sig-storage/csi-attacher:v3,4.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3,0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrador:v2.4.0
* NetApp/Trident-operador: 22.01.1 (opcional)




| v1.19.0  a| 
* NetApp/Trident:22.01.1
* NetApp/Trident-AutoSupport:22,01
* k8s.gcr.io/sig-storage/csi-provisionador:v2,2.2
* k8s.gcr.io/sig-storage/csi-attacher:v3,4.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3,0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrador:v2.4.0
* NetApp/Trident-operador: 22.01.1 (opcional)




| v1.20.0  a| 
* NetApp/Trident:22.01.1
* NetApp/Trident-AutoSupport:22,01
* k8s.gcr.io/sig-storage/csi-provisionador:v3,1.0
* k8s.gcr.io/sig-storage/csi-attacher:v3,4.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3,0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrador:v2.4.0
* NetApp/Trident-operador: 22.01.1 (opcional)




| v1.21.0  a| 
* NetApp/Trident:22.01.1
* NetApp/Trident-AutoSupport:22,01
* k8s.gcr.io/sig-storage/csi-provisionador:v3,1.0
* k8s.gcr.io/sig-storage/csi-attacher:v3,4.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3,0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrador:v2.4.0
* NetApp/Trident-operador: 22.01.1 (opcional)




| v1.22.0  a| 
* NetApp/Trident:22.01.1
* NetApp/Trident-AutoSupport:22,01
* k8s.gcr.io/sig-storage/csi-provisionador:v3,1.0
* k8s.gcr.io/sig-storage/csi-attacher:v3,4.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3,0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrador:v2.4.0
* NetApp/Trident-operador: 22.01.1 (opcional)




| v1.23.0  a| 
* NetApp/Trident:22.01.1
* NetApp/Trident-AutoSupport:22,01
* k8s.gcr.io/sig-storage/csi-provisionador:v3,1.0
* k8s.gcr.io/sig-storage/csi-attacher:v3,4.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3,0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrador:v2.4.0
* NetApp/Trident-operador: 22.01.1 (opcional)


|===

NOTE: No Kubernetes versão 1,20 e posterior, use a imagem validada `k8s.gcr.io/sig-storage/csi-snapshotter:v4.x` somente se a `v1` versão estiver atendendo ao `volumesnapshots.snapshot.storage.k8s.io` CRD. Se a `v1beta1` versão estiver servindo o CRD com/sem a `v1` versão, use a imagem validada `k8s.gcr.io/sig-storage/csi-snapshotter:v3.x`.
